/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;

export const idlService = IDL.Service({
  'addTopic' : IDL.Func([IDL.Text], [], []),
  'getDueReminders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getStudyProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(Time, IDL.Nat))],
      ['query'],
    ),
  'getTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'markReminderDone' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  
  return IDL.Service({
    'addTopic' : IDL.Func([IDL.Text], [], []),
    'getDueReminders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getStudyProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(Time, IDL.Nat))],
        ['query'],
      ),
    'getTopics' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'markReminderDone' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };